### ISSUE TITLE
Add information on how to securely store API keys/pass

### ISSUE THREAD

**Issue by TallGuysFreeADMIN** [discordjs/guide#100]
Multiple servers were taken over recently. Many of them followed discordjs' guide on how to connect a bot.  While looking it over, I see no information or warning to keep your credentials secure (.gitignore, system variable, pass thru commandline, etc). 
People are hardcoding keys into public git repos and being taken over. Please consider adding a warning and ways to securely store auth keys.

**Comment by Danktuary** [comment]
In [one of the very first few pages of the guide](https://discordjs.guide/#/preparations/setting-up-a-bot-application?id=your-token), there's a section explaining everything about your token. What it is, why you should keep it safe, and an example of what can happen if someone gets a hold of your token. Under the "What is a token, anyway?" section, all of this is very clearly stated.

> A token is essentially your bot's password; it's what your bot uses to login to Discord. With that being said, **it is vital that you do not ever share this token with anybody, purposely or accidentally**. If someone does manage to get a hold of your token, they can use your bot as if it were theirs—this means they can perform malicious acts with it.

Committing your token to your bot's repo is essentially the same as committing your day-to-day password to any other repo you make.

If people have skipped over this section of guide, that's not our fault; the content is there and it's up to the reader to choose if they want to read it or skip over it. I'd also like to add that we don't mention Git anywhere in the guide, which is why there's no mention of using `.gitignore`. As soon as you start using Git, it's up to you to figure out how to handle these things.

With all this being said, if you wish, you're very welcome to open a PR to add some sort of information about keeping them safe. If you choose to do so, I'd recommend putting it on the [configuration files](https://discordjs.guide/#/creating-your-bot/configuration-files) page.

**Comment by orderbs** [comment]
Some points to consider:

- Given the scale and nature of this attack, the status quo is perhaps insufficient.
- Many people using this guide are inexperienced (which is why they're using a tutorial), so despite the very high quality of the guide, some will have almost no real understanding of the tutorial code they might upload.
- At multiple points in the guide, one is linked here (i.e. GitHub), presenting the temptation to just fork/copy this repo and swap in one's token.  This seems less of a case where people are "skipping over" warnings but rather not fully comprehending what it means to upload unsanitized tutorial code to a public repo (like this).
- Obvious is in the eye of the beholder.
- It's not your fault (it's not your fault).
- Feedback is important, especially when invited.

Thanks for all your hard work, this is one of best-written guides out there.

Cheers!

**Comment by Danktuary** [comment]
@TallGuysFreeADMIN @orderbs We (the core team that work on the guide) are currently discussing what to do about this. At the very least, we'll add in a tip on the token section linked above stating something along the lines of "Hey, click here to read more about configuration files and how to keep your token secure", and on the configuration files page, add a tip about `.gitignore` or a section about using environment variables as an alternative.

However, I brought up an idea for a page entirely about security and risks in bot development. Things like this token incident, JavaScript's `eval()` function and its dangers, ratelimits and API spam, and the like. I'm not sure if we'll go through with making this page, but if you guys have something you'd like to see covered on the page, please do share your thoughts.

And as always, pull requests are always welcome. We're generally open to ideas and additions that benefit the guide and its users.
I'll re-open this for the time being and close it once we go through with one of the plans mentioned above. Thank you. 😄

**Comment by brandondavid** [comment]
I would like to help resolve this issue.  Does anyone want to discuss ideas before I dive in?

For example, would it be valuable to simply comment the sample code at appropriate points with a big warning that points to [/implementing-your-config-file](https://discordjs.guide/#/creating-your-bot/configuration-files?id=implementing-your-config-file)?

**Comment by TomSputz** [comment]
> At multiple points in the guide, one is linked here (i.e. GitHub), presenting the temptation to just fork/copy this repo and swap in one's token. This seems less of a case where people are "skipping over" warnings but rather not fully comprehending what it means to upload unsanitized tutorial code to a public repo (like this).

If this is actually a common problem in forks of this repo, it might be a good idea to add a commit hook that will scan the changes for a token.

**Comment by almostSouji** [comment]
> If this is actually a common problem in forks of this repo, how about adding a commit hook that will scan the changes for a token?

GitHub and Gist do this natively now, uploaded tokens are invalidated and the owner receives an Email about the incident with the link of the file.
ref: <https://help.github.com/en/articles/about-token-scanning>

What I said in https://github.com/discordjs/guide/issues/229#issuecomment-502099054 is still valid though, if anyone wants to try their hands on it feel free to submit a draft PR!

**Comment by conqr2** [comment]
Discord has implemented a system to fix this. Within minutes of your commit discord will auto-regen your token and DM you on discord

**Comment by tipakA** [comment]
Yes, that was already said in previous comment made in october.
