### ISSUE TITLE
Add a Help command with pages and categories

### ISSUE THREAD

**Issue by LucidiousXIV** [discordjs/guide#108]
I saw the guide for the help command and while it is basic, I think having one with Pages (Reactions) and Categories would also be very beneficial as it would look more clean and sleek. Would recommend be used with Embeds (I.e RichEmbed)

**Comment by Drahcirius** [comment]
Discord has said that using reaction menus as buttons is not a use case of the API they want to encourage. I don't think this feature should get added to the guide unless discord comes out with actual buttons. 

https://github.com/discordapp/discord-api-docs/issues/182#issuecomment-262388833

**Comment by Danktuary** [comment]
Although I myself am fond of the idea and think it can provide a good UX boost to your commands, Discord seems to think otherwise. Maybe Discord will eventually add buttons and/or change their minds on the matter sooner or later. But for the time being, we'd rather not cover content that's against Discord's wishes.
