### ISSUE TITLE
Self assignable roles using reactions

### ISSUE THREAD

**Issue by ThePlayer0** [discordjs/guide#109]
It is a command that sends a message to a channel and adds reactions to it then when a user clicks on a reaction he gets a role when he clicks again the role is removed

**Comment by PLASMAchicken** [comment]
#106 ?

**Comment by queezly** [comment]
So sorry, i kind of gotgot to reply here, @ThePlayer0 
[ReactionCollector#remove](https://discord.js.org/#/docs/main/master/class/ReactionCollector?scrollTo=e-remove) is only available on the master branch of the library, so the second part of your feature idea can not easily be realized on stable.

The PR PLASMAchicken linked attempts to explain the procedure for adding a role on reaction.
The removal would look about the same but with a "remove" eventlistener.

**Comment by Danktuary** [comment]
Heyo, so sorry for the extremely late reply. But I think we're gonna turn away from stuff like this because of [Discord's stance of things like this](https://github.com/discordapp/discord-api-docs/issues/182#issuecomment-262388833). We try to keep the content we make within Discord's guidelines and intentions.
