### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by TinnyTerr** [discordjs/guide#1555]
### Is your feature request related to a problem? Please describe.

I was attempting to create a mute command and came over timeout. A option would be to set the time they are timed out however the guide has `member.timeout(60_000);` Is the underscore needed, how would I make it a option and those questions are the ones I've thought of.

### Describe the solution you'd like

Show IF the underscore is not needed and if it is easily customisable eg `member.timeout(60_000 * multiplier);` where multiplier is a maths operation to get it to a hour for example

### Describe alternatives you've considered

`member.timeout(60000 * multiplier); //60,000 representing a minute in milliseconds`
Demonstrates that it is customisable and doesnt need to have a underscore (I have not checked if it does btw this is just a suggestion if it does work like that)

**Comment by almostSouji** [comment]
The guide is aimed at beginners with discord.js, not people who haven't used the language. 
We do not explain base language features like strings, functions, and expressions. For the same reason explaining numbers feels out of scope for the guide. 

Using math expressions instead of a number is just base JS. At any point, an expression that evaluates to a number can be used instead of a number literal.
