### ISSUE TITLE
Webhooks and automatic social media posting/captcha

### ISSUE THREAD

**Issue by BossMK** [discordjs/guide#174]
Hello! I don't believe this section has been suggested (probably because its really easy and I just don't know what I am doing just yet), but one of the things I wanted to do with the discord bot I am coding is have it automatically send a youtube video that I've uploaded to a channel in discord, and the same could be for reddit, twitter etc...but I just don't understand how that would be done. I know it has something to do with RSS feed because after looking around in google, it was kinda hard to pinpoint some kind of template or something to understand what was going on (just joined the server and saw the webhook tutorials there, though I hope that isn't the only way to do something like this). Now Captchas is another thing, to keep a more secure discord server from bot raids, I think that would be a great addition to the guide...Something like, a storage of images put together according to a randomized password.

**Comment by almostSouji** [comment]
After some more consideration:
This guide aims to explain the basic idea behind base usage of discord.js
For automatic Media posting you'd need some listener or probe/hook to the service in question and forward it to a webhook via a POST request to its endpoint. While you can utilize discord.js to send and manage webhooks I don't think this is a base use case that should be covered on this guide.

--- 

<https://discordjs.guide/popular-topics/webhooks.html> might be of some use for those landing here because they are looking for an explanation of how to use discord.js with webhooks
