### ISSUE TITLE
Update section 'Storing data with Sequelize'

### ISSUE THREAD

**Issue by AndriyMeleshko** [discordjs/guide#182]
Hello. I want to offer an improved sample section #Storing data with Sequelize for https://discordjs.guide/sequelize/
I add the [sample.txt](https://github.com/discordjs/guide/files/2957779/sample.txt) file

**Comment by Drahcirius** [comment]
The reason the guide doesn't store `guild id` is because I made `name` the primary key to showcase how you can specify your own primary key, which you removed. Since `name` is unique, it wouldn't make sense for it to be a multi-guild bot. But primary keys are automatically indexed, which makes querying by that key extremely fast. So despite the annoyance that "name" is now unique across all guilds the bot is on, this table will scale to millions of tags with no problem. Your table however, will get slower and slower to query as you add more tags. 

I don't mention this in the guide since I do have a primary key, but you didn't define what the primary key is, so you unintentionally opted into sequelize's default primary key which is a wasted column since you can't really do anything with it. 

The ideal solution is actually to make `name` and `guild id` be a composite primary key or add a composite unique index on, but that's a bit beyond the scope of a starter tutorial.

**Comment by AndriyMeleshko** [comment]
Okay. Thank you!
