### ISSUE TITLE
Adding a section on handling timeouts

### ISSUE THREAD

**Issue by SvDvorak** [discordjs/guide#195]
Seeing as many, including myself, have had issues with getting ECONNRESET it might be worth adding instructions in the guide on how to best handle it. Even just a notice would have saved me a lot of time debugging (as the timout would only occur every 2-5 days).

It would hopefully decrease the number of people putting up related issues on the discordjs API.

**Comment by DevKurka** [comment]
Totally true. Completly forgot about handling that personally last time I was scripting the bot.
For anybody looking here who doesn't know a solution - just add an error event handler.

Client.on("event", console.error)

**Comment by SvDvorak** [comment]
That would just print the error though? Some info on restarting the client/process would also be helpful. Now I made my own solution which doesn't kill the process but continues to try to login again, with an increasing delay between each attempt (to not overload Discord which might already be swamped).

**Comment by DevKurka** [comment]
@svDvorak it just prints, but doesn't terminate. That's just an example so.

**Comment by almostSouji** [comment]
```js
// Add the following event listener to your code (outside of any other listeners) to handle 'error' events properly:
client.on('error', console.error);
```
If the "error" event is handled, the library (discord.js) will attempt to reconnect your bot and you will get a more useful error message.

How you handle it depends on you, fact is the lib will attempt to reconnect if you do.
"Useful" is relative here, the 'error' event emits on websocket connection errors, which is caused by an interruption of the websocket connection the the Discord API. There is (in most cases) nothing you can really do about it else than getting a better/more stable connection and handling it to have the lib attempt reconnects.

**Comment by SvDvorak** [comment]
Ah, I guess I got a bit confused by a discussion on a discordjs-issue, I thought it would only pass the error to the console. If letting the client handle the event on error makes the bot reconnect then that would work for me. Is there any info on number of reconnection attempts are made and at what interval?
