### ISSUE TITLE
Cooldown section, where if check for timestamps.has(message.author.id) does not work

### ISSUE THREAD

**Issue by Arxero** [discordjs/guide#197]
So [this is where I am ](https://github.com/discordjs/guide/blob/master/guide/command-handling/adding-features.md#cooldowns) and I can say that it does not work properly cause you never have message.author.id in the first place in timestamps collection up until this point.

And it will never enter those if therefore it won't show the message that is intended to show.

**Comment by Monbrey** [comment]
The code for adding message.author.id to the timestamps collection is further down the page, at the bottom of the Cooldowns section 

`timestamps.set(message.author.id, now);
setTimeout(() => timestamps.delete(message.author.id), cooldownAmount);`

**Comment by Arxero** [comment]
hmm, I know that, but then it gets deleted immediately and it never gets in that if before it :X

**Comment by Monbrey** [comment]
A timeout is set to delete it after the cooldown time has expired, not immediately. The default is three seconds, unless the command has a different cooldown set:

`const cooldownAmount = (command.cooldown || 3) * 1000;`

If this code isn't working for you, I recommend discussing it in the [Discord.js server](https://discord.gg/bRCvFy9). I can't see anything at fault in the guide.

**Comment by Arxero** [comment]
the code definitely ain't working for me, I know what the idea behind is but don't know why in my case I never have author id in my timestamps map.

**Comment by Danktuary** [comment]
It'd help if posted your current code. There's nothing wrong with that piece of code from the guide. Running `yarn init -y && yarn add discord.js && node .` inside the `code-samples/command-handling/adding-features` directory (after you put your token in the `config.json` file in the same folder) makes it run as intended.

![](https://i.imgur.com/iHMqihD.png)

If you comment out the if statement you mentioned, you'll never see that cooldown message, thus allowing commands to be spammed.

I'd suggest going through that section from the beginning and trying again. If you're still having issues, you can ask in the [d.js server](https://discord.gg/bRCvFy9). Thanks.

**Comment by Arxero** [comment]
thanks a bunch for the help I asked in the server and that guy Havoc helped me out.
![Screenshot_1](https://user-images.githubusercontent.com/30701352/55269391-296e1700-529b-11e9-96ec-9d4220a43347.png)
https://github.com/Arxero/mavbot/blob/master/index.js#L41
https://github.com/discordjs/guide/blob/master/code-samples/command-handling/adding-features/index.js#L15

I will be going there from now one, instead of spaming here. :-)

**Comment by lihuelworks** [comment]
Sorry to add to this, but on the same vein of timestamp questions, what exactly do **_timestamps_** and **_cooldown_** have inside?

Trying to print **_timestamp_** using spread _syntax_ and _entries()_ like so `[...timestamps.entries()]` gives my `message.author.id` (as expected, since it compares it on the if) and some random value (note, I put the console.log() after the timestamps.set(...) line as seen [here](https://github.com/discordjs/guide/blob/3d5e43db53230644f47feb21a85c4ea05b5314d8/code-samples/command-handling/adding-features/12/index.js#L70), otherwise it'd be empty):
```
timestamps inside:
        182923807449808914,1610093587419
```

---

While trying to print **_cooldowns_** Collection gives me the name of the command, and an [object Map] (also using spread syntax and entries), as seen here (I put this console.log() next to the **_timestamps_** console.log()):

```
cooldowns inside:        
        ping,[object Map]
```

In **_cooldowns_** case, there is a .set() [on line 54](https://github.com/discordjs/guide/blob/3d5e43db53230644f47feb21a85c4ea05b5314d8/code-samples/command-handling/adding-features/12/index.js#L54) that fills it with the command name and a new, empty Collection. But that collection is never filled. Why is that?

I know I might sound oblivious to of the guide explanations, but apart from the quick enumeration after the 3rd snippet on [Cooldown section ](https://discordjs.guide/command-handling/adding-features.html#cooldowns) (which cites **_timestamps_** as "A variable with the current timestamp."), there is not much explanation of what is going on inside.

If this type of questions must be asked on the Discord of the module, please let me know.

**Comment by almostSouji** [comment]
I see a lack of detail and clarity in this guide section, #564 will be used to track this.

Additionally, I provided a short answer to your question there - This is separate and a different issue from this thread, where the guide code simply was not applied correctly which caused issues due to scope lifetimes.
