### ISSUE TITLE
[help-needed] Dynamic Help Command with Categories

### ISSUE THREAD

**Issue by Joel-Cedras** [discordjs/guide#259]
I would like to know how to add categories to my help command and then each command in that category needs to be put under that category in the help embed.

I’ve added a “category: ""” under each command and some of them are filled in. Example: category: fun.

Any and all help will be appreciated.

**Comment by almostSouji** [comment]
Sorry you didn't receive an answer yet, I totally forgot about this.

Since commands are a collection you can use <https://discord.js.org/#/docs/main/stable/class/Collection?scrollTo=map> to very easily iterate over it and produce content from each element.
I'd suggest to map your command collection to an object, or possibly another Map/Collection where the commands are categorized (keyed) by category. (Collection<string, Collection<string, Command>>)
For the outer collection i'd suggest using the category name as key, and a collection of commands (key: commandName, value: command) as value.

The approach would work like this:
```
For each command
  If the collection already has its category name as key
    Add the command to that category
  Else 
    Make a new Collection (category name as key)
    Add the command to that collection

For each category (in this new collection)
  Print the name of the collection (+ additional formatting)
  For each command in this category
    print the the command name (+ additional formatting)
```

```js
// .category would be a category name, as you described above
const { Collection } = require("discord.js")
const categories = new Collection()

commandCollection.forEach(command => {
  const category = categories.get(command.category)
  if (category) {
    category.set(command.name, command)
  } else {
    categories.set(command.category, new Collection().set(command.name, command))
  }
})
```

A really simple approach to mapping could be the following (can be heavily adapted of course):

```js
const lines = categories.map((category, id) => `${id}: ${category.map(command => command.name)}`)
channel.send(lines.joing("\n")) // joining the command by new line, so each category has its own line
```

Since this has been open for some while I'll close the issue 
References for Collection:
https://discord.js.org/#/docs/main/stable/class/Collection
And since Collection is a base JS Map with convenience methods borrowed from Array, you'll find a lot of examples and more in-depth explanation on the respective documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
