### ISSUE TITLE
Branch selectors and UX

### ISSUE THREAD

**Issue by almostSouji** [discordjs/guide#273]
When starting to adapt the tags and information on the discord server I noticed that pointing people to a page and telling them to make sure to select the right version is not very user friendly.
Thinkable solutions: verbose URL containing the branch; (optional) query parameter determining a branch.

Another thing that's missing in the current system is some indicator for the user as of which branches of the guide they are currently viewing. Currently you land on the page, the selector is hidden behind the gear icon and you have no idea what you have selected.
Thinkable solutions: verbose branch name next to the left header in the top nav, color indicator for versions (discord.js blue for stable, red/orange? for master) - possibly reusing forced styles

**Comment by Danktuary** [comment]
> Thinkable solutions: verbose URL containing the branch;

I think this would break a lot of the existing links and probably affect SEO, which I want to avoid. And possibly a pain to implement due to the guide using VuePress and not being a custom Vue app.

>  (optional) query parameter determining a branch.

Do-able, but would immediately go away once you click on a different page or even scroll down to a different header area. The only thing this would change is that I could make it select your version based on the query parameter, which isn't entirely necessary when there's a UI for it, but may help with this point here:

> I noticed that pointing people to a page and telling them to make sure to select the right version is not very user friendly.

I'm not against it; if others think it'd help, I won't mind adding it. Accepting `?v=12` and `?version=12` could work.

> Another thing that's missing in the current system is some indicator for the user as of which branches of the guide they are currently viewing. Currently you land on the page, the selector is hidden behind the gear icon and you have no idea what you have selected.

Yeah, this is a bit of a fault. I remember commenting this here: https://github.com/discordjs/guide/pull/218#issuecomment-497979720
I think just adding it to the left of the gear would be most ideal. A solution to the mobile resolution issue would be to maybe use the [guide logo icon](https://github.com/discordjs/guide/blob/master/guide/images/branding/book-small.png) on smaller resolutions instead of having just the "Discord.js Guide" text. I suppose the logo text doesn't matter very much as opposed to a feature like this.
