### ISSUE TITLE
`TypeError: member.user.displayAvatarURL is not a function`

### ISSUE THREAD

**Issue by goldentg** [discordjs/guide#290]

**Comment by almostSouji** [comment]
> member.user.displayAvatarURL is not a function

It is a property on version 11.x and a method (with various options) in version 12.
If you are using version 11 of discord.js please make sure to select the respective 
version on the guide (top bar drop-down)

![firefox_RDWt0Nvipu](https://user-images.githubusercontent.com/26532370/69175170-8c9b0b00-0b03-11ea-915b-9a281ac707c6.png)

<https://discord.js.org/#/docs/main/stable/class/User?scrollTo=displayAvatarURL>
vs v12: <https://discord.js.org/#/docs/main/master/class/User?scrollTo=displayAvatarURL>

If you have general discord.js questions you should consider joining the discord server and asking there instead of github: https://discord.gg/bRCvFy9
