### ISSUE TITLE
Oauth2 bug

### ISSUE THREAD

**Issue by warstrolo** [discordjs/guide#348]
The Oauth2 code is not working, 
when i login, it doesn't change the page 
![image](https://user-images.githubusercontent.com/58334832/76427617-d490b700-63ac-11ea-875f-7cb9ebc5f490.png)
Pls help

**Comment by Monbrey** [comment]
In future please don't remove the issue template, it exists for a reason.
You should also provide a reproducible code sample so that we can assist in debugging.

Having said that, I'm unable to see any problems here. The URL clearly shows the `?code=` query string parameter, which means Discord has authorized you and returned you to the `redirect_uri` that you specified and listed in the Developer Portal.

You're now supposed to extract the code from the query parameters, and use it to exchange for an access token. This step is detailed here: https://discordjs.guide/oauth2/#oauth2-flows

**Comment by almostSouji** [comment]
At this state I don't think this qualifies as bug in the guide for now
If you have more details and can still reproduce this behavior after following each step carefully once more, feel free to re-open
