### ISSUE TITLE
how do I get shard id

### ISSUE THREAD

**Issue by Shadowplays4k** [discordjs/guide#419]
so in v11 everything was simple

client.shard.id gives you the id in v11 but it was removed

so how do I get the id in v12????

**Comment by almostSouji** [comment]
If you look at the [documentation ](https://discord.js.org/#/docs/main/stable/class/ShardClientUtil) for a single second you will find a property that looks quite familiar, however with an added **s** at the end, denoting a plural, since support for different approaches to sharding have since been added to the library.

Alternatively the change is listed in https://discordjs.guide/additional-info/changes-in-v12.html#shardclientutil-id.
