### ISSUE TITLE
The prune command from the guide says I need to enter a number from 1-99 when I did prune 1

### ISSUE THREAD

**Issue by JavascriptLearner815** [discordjs/guide#458]
**Describe the bug**
This prune command misfired "you need to enter a number between 1 and 99." when I supplied the number 1.

**To Reproduce**
1. Use the command '!prune 1'
2. See reply

**Screenshots**
![#speedo-bot-commands - Discord 8_14_2020 12_28_19 PM](https://user-images.githubusercontent.com/59782978/90276687-ebd74300-de29-11ea-9d77-390b09b79a80.png)

**Device (please complete the following information):**
 - Device/OS: HP Slim Desktop 290-a0xxx
 - Browser: chrome
 - Version: 1909

**Additional notes**
Link to the guide page: https://discordjs.guide/creating-your-bot/commands-with-user-input.html#caveats-2
Link to my server if you want to see it: ---snip---

I _suggest_ you change the guide to say `else if (amount < 1 || amount > 100) { return message.reply('you need to input a number between 1 and 99.'); }` (this worked for me)

Feel free to ask for more clarification, for example, on the code I have, etc.

**Comment by HarmoGlace** [comment]
It works as inteded, pruning only 1 message is useless, it is like if you delete it manually...

**Comment by NotSugden** [comment]
> between 1-99
the message says between 1-99, not just 1-99, there is no issue here

**Comment by JavascriptLearner815** [comment]
> It works as intended, pruning only 1 message is unnecessary, it is like if you delete it manually...

Then why does the message say from 1-99 when it should say 2-99?

> > between 1 and 99
> 
> the message says between 1 and 99, not just 1 and 99, there is no issue here

99 works and 1 doesn't, also that is not what I said. The message needs to be updated to 2-99 or the check needs to be updated.

**Comment by HarmoGlace** [comment]
No, because it is ]1, 99]

**Comment by JavascriptLearner815** [comment]
Also look at #450

**Comment by almostSouji** [comment]
Using the provided guide "resulting code" sample directly without modification save the token and prefix I can not at all reproduce this. (see gif below)

--- 

> It works as intended, pruning only 1 message is unnecessary, it is like if you delete it manually...

> Then why does the message say from 1-99 when it should say 2-99?

> 99 works and 1 doesn't, also that is not what I said. The message needs to be updated to 2-99 or the check needs to be updated.

These are all under the (wrong) assumption that `prune 1` is not a valid command. As I demonstrated in the gif below (and explain further down) this is not true. If your bot behaves like this you did not follow the guide correctly and likely forgot to increment amount (more about why we do this: see below)

--- 

Firstly: what the guide tells you:

If you actually read and apply the full guide section correctly you will not end up with that issue, the guide already covers why we increment: 

> The other caveat with this is that the !prune {number} message you sent will also count towards the amount deleted. What this means is that if you send !prune 2, it'll delete that message and only one other. There are a couple ways around this, but we'll be taking the easiest route for the sake of the tutorial. Here are the edits to make to your current code:
```diff
- const amount = parseInt(args[0]);
+ const amount = parseInt(args[0]) + 1;
```
```diff
- else if (amount < 2 || amount > 100) {
-	return message.reply('you need to input a number between 2 and 100.');
- }
+ else if (amount <= 1 || amount > 100) {
+	return message.reply('you need to input a number between 1 and 99.');
+ }
```

We use diff codeblocks to achieve a red and green highlighting for parts of the guide you need to change, meaning the red `-` prefixed part is what you should already have in your code from following previous sections. This instruction now tells you to remove these lines of code and add the green `+`  prefixed lines (essentially replacing them)

--- 

Alas I will try to break the check down and explain why it works and why your suggestion does not make much sense:

Let's start with a gif displaying the behavior:

![demo](https://user-images.githubusercontent.com/26532370/91356552-252b8d80-e7f0-11ea-97bf-ecdba3741047.gif)

I want to stress again that I ran the exact code from the resulting code samples page (and verified that it is indeed exactly what the guide says) meaning you should end up with the exact same code and the exact same behavior if you carefully follow this guide.

- `prune 1` removes 1 of the original messages (+ the command message)
- `prune 2` removes 2 of the original messages (+ the command message)
- `prune 0` will return the notice to pick a number between 1 and 99

Since #bulkDelete is capped at 100 messages per call we need to cap it at 99 for user input (we want to delete the command message as well, after all)

`amount` in the code does not refer to the number the user specified, but to `parseInt(args[0]) + 1` and already accounts for the users command message.

- `prune 1` will result in `amount = 2` (valid)
- `prune 2` will result in `amount = 3` (valid)
- `prune 100` will result in `amount = 101` (this is invalid, we can at max prune 100)

Resulting the check "amount lower than or equal to 1" is correct. If you get `amount = 1` you have put in `prune 0`, this is invalid.

Your suggestion `<1` would mean that `prune 0` is valid and just prunes the command message, however that input from a user experience view is pretty nonsensical. Again, "amount" refers to the already incremented number, not the direct user input. 

Resulting the check "amount higher than 100" is correct. If you get `amount = 100` you inserted `prune 99`, we can prune that, no issue. If you get `amount = 101` (greater than 100) you put in a number that's greater than 99, this too is invalid, since we deliberately want to restrict this feature to a single API call which at most allows 100 messages.
