### ISSUE TITLE
A prefix command with MongoDB

### ISSUE THREAD

**Issue by DemonWolfFang** [discordjs/guide#479]
It'd be nice to see a tutorial using MongoDB for a prefix command so other servers can change a bots prefix. Where users don't want to use SQLite or can't use a JSON file for it.

**Comment by code913** [comment]
I'm on it. ~~even though I am not a discordjs.guide contributor~~

**Comment by storate** [comment]
I don't think that fit in the context of the discord.js guide. The guide is mainly there to provide help with using the library itself, and an advanced implementation such as MongoDB would be a bit out of scope. Of course, there are some parts that cover database-wrapping modules like Sequelize and Keyv, but I suspect that is only because they want to demonstrate how to be able to easily store persistent data.

Additionally, there is plenty of [good documentation and guides](https://docs.mongodb.com/guides/) available for services like MongoDB, which will walk you through some possible use cases (which you can then implement into your project.)
