### ISSUE TITLE
The discordjs.guide part when working with audit logs in regards to who kicked a user is wrong?

### ISSUE THREAD

**Issue by FredTheNoob** [discordjs/guide#505]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
![image](https://user-images.githubusercontent.com/43958385/95771181-e88df580-0cba-11eb-8962-170ec49bc6fa.png)

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment]
pretty sure that's covered by this?

> In the following examples, a very simple case for some auditLog types will be explored. Some basic error handling is performed but these code segments are by no means fool proof and are meant to teach you how fetching audit logs work. For a rigorous system you will most likely need to expand on the examples based on your own goals.

you could compare the entry's createdAt property to the current time to check that, but it's an edge case anyway.

**Comment by almostSouji** [comment]
Kicks and voluntary leaves are not discernible in the event, Leaves do not cause an audit log, thus it will fetch the kick entry, as you have observed. The targeted functionality is not very reliable due do this caveat. You can improve the accuracy with timestamps but even with that an arbitrary threshold of accuracy is given.

There isn't really a final solution to ensure this reliably due to how the discord handles this data (time between websocket event and audit log is arbitrary - audit logs are not even guaranteed to ever arrive, no logs for non-moderative causes)

We can't fully cover every single edge case on the guide. The introductory paragraph given thus explains that this is a very rough base on how to work with audit logs (fetch them, inspect them and their structure) to then make your own decisions about accuracy and find good-enough trade-offs for your use case.
