### ISSUE TITLE
Bug Report –– node-fetch Examples

### ISSUE THREAD

**Issue by SimpleDeveloping** [discordjs/guide#546]
*Bug Report*
When following the guide for both the Random.cat and Urban Dictionary, the guide uses _await_, but is not inside of an async function, hence both commands do not work whatsoever.

Version 12 of Discord.js

**Comment by almostSouji** [comment]
The code is wrapped into an async event callback as described in the [skeleton code section](https://discordjs.guide/additional-info/rest-api.html#skeleton-code) just above. The `// ...` is where the respective code goes. At this point of the guide you should already have an understanding of how commands work ("message" event callback, some parsing of the message content into prefix, command and rest and so on). Otherwise I'd suggest starting at the top of the guide, which covers this all in much greater detail.

**Comment by JeffReeves** [comment]
I've followed the guide for dynamic commands, and I'm stumped on how to make the execute section asynchronous so that I can use the await fetch for the cat demo. How is this done?

I've combed through the documentation and there doesn't seem to be any good example of this.
