### ISSUE TITLE
Some stuff in Discord.js V12 not working

### ISSUE THREAD

**Issue by WolfGames** [discordjs/guide#548]
Hi
My bot stopped working after this update.
I aDdEd EvErYwHeRe **.cache** and its ok
But some stuff still not working:
- client.user.setPresence({ status: 'Online', game: { name: "Game status" }}) not displaying status and any error
- **message.author** when included in message, displaying wierd numbers instead of **@user**
-message.author.send("DM Messages to message author")

Other:
-client.on('ready', () => {//Some bot start code here}) function reacting slower than before update

Maybe im just doing something wrong but i cant find any help in the internet, so i think its a bug.
I visited this page: https://discordjs.guide/additional-info/changes-in-v12.html#before-you-start

**Comment by tipakA** [comment]
For the `setPresence()`: https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setPresence (check what `PresenceData` is and/or look at the example;
For the `message.author`: https://discordjs.guide/additional-info/changes-in-v12.html#string-concatenation;

For the ready being slower, thre isn't much you can do about that, probbaly because library does different things before emitting ready since on v12 than on v11.

Additionally, even if it would be a bug, the guide repository isn't really a place for such reports. Also, you probably should ask in the [Discord server](https://discord.gg/bRCvFy9) before opening issues.

**Comment by WolfGames** [comment]
Thanks!
Now im 100% sure its not bug.
Thanks a lot
