### ISSUE TITLE
Misuse of the ?. in examples

### ISSUE THREAD

**Issue by tguichaoua** [discordjs/guide#728]
**Describe the bug**

Misuse of the `?.` operator in some examples.
When `?.` is used, all following `.` should be `?.`

For example:
https://github.com/discordjs/guide/blob/8e0b56137f162d35c208ac8cd5738a5242debe86/guide/interactions/registering-slash-commands.md

```ts
if (message.content.toLowerCase() === '!deploy' && message.author.id === client.application?.owner.id) {
```
Should be:
`client.application?.owner?.id`

I didn't check all the guide.

**Comment by monbrey** [comment]
> When `?.` is used, all following `.` should be `?.`

This isn't correct. The optional chaining operator stops evaluating anything further if it evaluates to `null` or `undefined`.

`ClientApplication#owner` is not a nullable property, so it doesn't need to be optional chained.

**Comment by tguichaoua** [comment]
I have got an error with TypeScript
![image](https://user-images.githubusercontent.com/33934311/126892879-2dcb2c87-a58c-456e-96c9-ff0c4f91c2ca.png)

**Comment by almostSouji** [comment]
Okay, review time. So

> When ?. is used, all following . should be ?.

No, evaluation stops when encountering the first null value

> ClientApplication#owner is not a nullable property, so it doesn't need to be optional chained.

It is in [v13](https://discord.js.org/#/docs/main/master/class/ClientApplication?scrollTo=owner), you were probably looking at v12, where it was guaranteed because the application hat to be fetched in order to get to it at all (and the owner is in the fetch payload)

However the property is guaranteed after ready (so by extension in any event callback, here `"messageCreate"`), which makes this unnecessary in JS, however will cause an issue in TS and can be [asserted](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) since it is known to be present in this context.

**Comment by mjfwebb** [comment]
@almostSouji I am actually receiving the following Typescript error when I do not include two optional chaining operators:
![image](https://user-images.githubusercontent.com/28074382/129095192-b5af093b-8743-4edf-891d-61e0f250bee8.png)

The fix to that error to add the additional `?`:

```
if (message.content.toLowerCase() === '!deploy' && message.author.id === client.application?.owner?.id) {
```

Do you have any thoughts on this? Is this a TS issue?
