### ISSUE TITLE
Include a subsection on subcommands.

### ISSUE THREAD

**Issue by MattA-Official** [discordjs/guide#754]
**Problem**
Currently, subcommands are only mentioned in [registering-slash-commandsl#option-types](https://discordjs.guide/interactions/registering-slash-commands.html#option-types) and you are referred to the Discord API for further information. This is fine, however, you have to go searching the documentation for how to find which subcommand a user opted to select.

**Prefered Solution**
In [replying-to-slash-commands#parsing-options](https://discordjs.guide/interactions/replying-to-slash-commands.html#parsing-options) there should be a short section explaining how to get the subcommand (or subcommandGroup) via `.getSubcommand()` or `.getSubcommandGroup()`

**Alternatives**
Keep it as is and allow people to navigate to the [`CommandInteractionOptionResolver`](https://discord.js.org/#/docs/main/master/class/CommandInteractionOptionResolver) on the documentation and find the relevant methods there.

**Additional Notes**
I would be happy to provide a PR if this is a change that you would like to make.

**Comment by Danktuary** [comment]
Originally it was my decision to leave it at just a link to the Discord API docs, but now I think this would be a good addition. I discussed it with @adrifcastr and they also think a page showcasing a subcommands example would be ideal.

I'll assign them to this issue so that they can take care of it as they see fit. Thanks for the request. 👍🏼
