### ISSUE TITLE
Search doesn't work when I click it and the search was meant to do in same page

### ISSUE THREAD

**Issue by sayantan300** [discordjs/guide#794]
The search works when i click other pages in search results, but if the result is in the current page that I'm on, it doesn't change the `https://discordjs.guide/<current page>#heading` this heading doesn't change. I checked address bar and it's not changed there.

**Comment by DET171** [comment]
I would say that this is a problem with Algolia and not the guide itself....

**Comment by sayantan300** [comment]
But it is a bug :(

**Comment by Danktuary** [comment]
This is a weird one because it works when you use the arrow keys and press enter. If you pay attention to the address bar, when you click on a result inside the same page, it does change but quickly changes back to your current header.

I tried disabling the theme in the `config.ts` file, but it happens with the default theme too. It'd have to do with the [`@vuepress/plugin-docsearch` files](https://github.com/vuepress/vuepress-next/tree/main/packages/%40vuepress/plugin-docsearch).

What's even weirder is that it does work on the [VuePress v2](https://v2.vuepress.vuejs.org/) site. Not sure about this one.

**Comment by sayantan300** [comment]
Also, btw, if I visit `https://discordjs.guide/<any page>#any-heading` then it will scroll to the any-heading page (as normal) but there's a wierd border on the title... Is this normal?

**Comment by DET171** [comment]
Yes, its very normal. It's a Vuepress thing that isn't very editable.

**Comment by almostSouji** [comment]
Supposedly upstream, don't see how we'd fix that on our end.
(If that's the case, sanc can reopen)
