### ISSUE TITLE
Little typing fault

### ISSUE THREAD

**Issue by Koenie06** [discordjs/guide#804]
**Describe the bug**
At the site/guides at https://discordjs.guide/popular-topics/reactions.html#removing-reactions-by-user and then scrolling down to 'awaiting reactions' you have the part of the 'const filter' that is 'user.id === interaction.user.id' while using above 'message' and not a interaction. I know that the message maybe is the fetched interaction, but it isn't said in the guides. 

**To Reproduce**
 in the 'const filter' part user.id === interaction.user.id

**Device (please complete the following information):**

**Additional notes**

**Comment by WiseDevHelper** [comment]
The code snippet is correct, as the `message` is the fetched `interaction`. This is because all the previous code snippets on the page are `interaction` based. You can confirm also this by checking out [the code samples.](https://github.com/discordjs/guide/blob/main/code-samples/popular-topics/reactions/13/awaiting-reactions.js)
