### ISSUE TITLE
Command chapters are out of order/missing?

### ISSUE THREAD

**Issue by Lombra** [discordjs/guide#810]
Hi,

I'm about to upgrade to version 13, and decided to go through the guide to see how some new stuff is meant to be implemented. Got very confused trying to read all the chapters on commands in order.

The very first meaningful thing you're taught to do is to [listen for `interactionCreate` events](https://discordjs.guide/creating-your-bot/#listening-for-interactions). Couple of chapters later you get to [add more commands](https://discordjs.guide/creating-your-bot/adding-more-commands.html), on top of your supposedly already existing ping command, the implementation of which I did not see covered until now. (seems to be covered in the [chapter following this one](https://discordjs.guide/command-handling/))

This seems to be refering to slash commands as it consistently mentions interactions, but I'm assuming this used to be chapters on how to implement message commands, which has since been updated, especially considering how the "add more commands" section seems to imply that that's (`if "cmd" then reply()`) all that's required to implement slash commands. (unless, of course, I've completely overlooked something regarding how slash commands work)

Finally, the Command handling section covers how to separate (slash) commands into different files, but you're not truly introduced to the concept of slash command until later, in [Registering slash commands](https://discordjs.guide/interactions/registering-slash-commands.html).

I don't have a specific suggestion as to what to do about it. I guess firstly, the order in which chapters are laid out needs to be looked over. And secondly, one needs to consider whether the early parts were actually meant to be about message commands rather than slash commands, and whether message command guides should still exist, or be replaced entirely by slash commands.

**Comment by Danktuary** [comment]
Hi, this was an issue with our upgrade process from v12 to v13. The old code and paragraphs were meant to work for the `messageCreate` event, and as such would rely on you creating the event listener and then sending a message in your Discord server to test it out.

Since we opted to move for full-on slash commands, this no longer works; you must first register a slash command before testing the `interactionCreate` event and replying to commands.

I rewrote the `/creating-your-bot/` pages in #826 to bring things back to a proper flow. A command deployment script that allows you to register slash commands is demonstrated before any `interactionCreate` listener is mentioned. The command handling page has also been moved inside that category and includes its own (very similar) deployment script.

Please check it out and let me know what you think. Thanks! 😄
