### ISSUE TITLE
Per Server Settings With Sequelize

### ISSUE THREAD

**Issue by TBNRItzDoge** [discordjs/guide#86]
Please add a page for this, would be appreciated.

**Comment by Drahcirius** [comment]
Although it doesn't explicitly do so, the current sequelize guides already provide you all the knowledge and tools to create per-server settings. It covers creating schemas with different attribute types, querying with conditions, and manipulating the results of the queries and saving them. If you can follow the tutorial, you should also be able to modify the tutorial code so that it's tailored to your specific needs.

I don't see the need the add an additional page that duplicates an existing page except with different columns.

**Comment by Danktuary** [comment]
Adding on to what Drahcirius said, the only real work you'd need to do is add a column for storing the guild ID, and then fetching a row with the guild ID whenever you need it. The base info exists, so just apply it to fit your situation. 👍
