### ISSUE TITLE
The event handling page's github example is lacking

### ISSUE THREAD

**Issue by Midaswili** [discordjs/guide#950]
The github page there seems to omit many files and gets rid of huge sections of the code— that cause your bot to not work.

**Comment by J-Human** [comment]
Excluding the `config.json` file, all files in this repository and online are identical, plus each has 3 files. Could you explain in depth which one exactly is causing your problem? 

Or... perhaps you are talking about the first code block in here - https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files? The `package*` files, as well as the `node_modules` folder are there, since it is assumed you have followed the instructions in https://discordjs.guide/preparations/. It's also assumed you placed the necessary credentials in JSON file.

Oh! It is also possible you might be talking about the stripped off code in https://discordjs.guide/creating-your-bot/event-handling.html#reading-event-files. In that case, you are expected to copy the starter code listed at the top of the page.

**Comment by almostSouji** [comment]
We don't list the full code snippet every time to keep code blocks as short and as little disruptive as possible. If you encounter missing instructions or code please be more specific about which guide section and (optimally) which code you are referring to and elaborate on why you think it should be added.
